42 persisting data about the webhooks
Transfa/sendhooks-engine pull request #52
Opened 2023-11-23 16:09 UTC by gjivaros

2023-11-23 16:11 UTC, koladev32 commented
Can you provide a quick README on how to spawn and start the project ? With docker and the docker image of sendhooks engine too

2023-11-23 16:17 UTC, gjivaros commented
> Can you provide a quick README on how to spawn and start the project ? With docker and the docker image of sendhooks engine too

ok

2023-11-23 20:18 UTC, gjivaros commented
@koladev32 done

> Can you provide a quick README on how to spawn and start the project ? With docker and the docker image of sendhooks engine too

@koladev32 done

2023-12-05 06:46 UTC, LewisYann requested changes
somes changes request

2023-12-05 06:46 UTC, LewisYann commented on api/src/configuration.ts
> +    host: strVal(process.env.REDIS_HOST),
```suggestion
    host: String(process.env.REDIS_HOST),
```
n'aurait pas suffit ?

2023-12-05 06:46 UTC, LewisYann commented on api/src/configuration.ts
> +    port: nbVal(process.env.PORT),
```suggestion
    port: Number(process.env.PORT),
```
n'aurait pas suffit ?

2023-12-05 06:46 UTC, LewisYann commented on api/src/configuration.ts
> +    port: nbVal(process.env.PORT),
```suggestion
    port: Number(process.env.PORT),
```
n'aurait pas suffit ?

2023-12-05 06:46 UTC, LewisYann commented on .gitignore
>  #  binary files
J'ai l'impression qu'il a un eof ici

2023-12-05 06:46 UTC, LewisYann commented on .gitignore
>  #  binary files
J'ai l'impression qu'il a un eof ici

2023-12-05 06:46 UTC, LewisYann commented on .gitignore
>  #  binary files
J'ai l'impression qu'il a un eof ici

2023-12-05 06:46 UTC, LewisYann commented on .gitignore
>  #  binary files
J'ai l'impression qu'il a un eof ici

2023-12-05 06:46 UTC, LewisYann commented on api/docker-compose.yml
> +version: '3.9'
J'ai l'impression qu'il a un eof ici

2023-12-05 06:46 UTC, LewisYann commented on api/docker-compose.yml
> +      - PORT=5001
Il serait mieux d'avoir ceci dans un fichier d'environnement

2023-12-05 06:46 UTC, LewisYann commented on api/docker-compose.yml
> +      - "5002:5001" # the default port for accessing from the localhost is 5001. The service inside docker can be accessed from the port 5000.
Le commentaire ne match pas 👀

2023-12-05 06:46 UTC, LewisYann commented on api/docker-compose.yml
> +      - "5002:5001" # the default port for accessing from the localhost is 5001. The service inside docker can be accessed from the port 5000.
Le commentaire ne match pas 👀

2023-12-05 06:50 UTC, LewisYann commented
> _ No description provided. _
@gjivaros 
J'ai remarqué une .env  sur le repos. Il devrait t'avoir echapper. Tu pourrai deja ajouter un env.sample dans une premier temps, et décrire dans ton readme le process pour le setup. Ça sera plus safe

2023-12-25 14:24 UTC, gjivaros commented on api/src/configuration.ts
> +    host: strVal(process.env.REDIS_HOST),
Ce sont des helpers qui font un checking de l'existence et du typage de la variable d'environnement. En utilisant Numéro ou String ça ne vérifie pas l'existence de la variable

2023-12-25 14:25 UTC, gjivaros commented on api/src/configuration.ts
> +    port: nbVal(process.env.PORT),
Ça va retourner un NaN si la variable d'environnement n'existe pas

2023-12-25 14:25 UTC, gjivaros commented on api/docker-compose.yml
> +      - PORT=5001
Ok

2023-12-25 16:05 UTC, gjivaros commented on api/src/configuration.ts
> +    host: strVal(process.env.REDIS_HOST),
@LewisYann

2023-12-25 16:05 UTC, gjivaros commented on api/src/configuration.ts
> +    port: nbVal(process.env.PORT),
@LewisYann

2023-12-25 16:05 UTC, gjivaros commented on api/src/configuration.ts
> +    port: nbVal(process.env.PORT),
@LewisYann

2024-01-12 21:52 UTC, merged